language: node_js
node_js:
  - "6"
  - "8"
  - "node"
matrix:
  allow_failures:
    - env: TRAVIS_NODE_VERSION=node
services:
  - postgresql
before_script:
  - psql -U postgres        -c 'CREATE DATABASE pgx;'
  - psql -U postgres -d pgx -c 'CREATE TABLE kv (key TEXT NOT NULL PRIMARY KEY, val TEXT NOT NULL);'
addons:
  postgresql: "9.4"
env:
  - DATABASE_URL="postgres://postgres@localhost/pgx"
